[package]
name = "unilang"
version = "0.1.0"
edition = "2024"
channel = "nightly"
[dependencies]
chrono = "0.4.42"
escape_string = "0.1.2"
nonempty = "0.12.0"
regex = "1.11.2"
rustc-literal-escaper = "0.0.4"
strum = { version = "0.27.2", features = ["derive"] }
